# ============================================================
# Global
# ============================================================
acr: ireneandjoaoacr.azurecr.io
secret: 'ireneandjoao_secret_key'

# ============================================================
# MongoDB
# ============================================================
mongodb:
  uri: 'mongodb://localhost:27017/restauranty'

# ============================================================
# Microservices
# ============================================================
auth:
  image: ireneandjoaoacr.azurecr.io/restauranty-auth
  tag: latest
  port: 3001
  replicas: 1

discounts:
  image: ireneandjoaoacr.azurecr.io/restauranty-discounts
  tag: latest
  port: 3002
  replicas: 1

items:
  image: ireneandjoaoacr.azurecr.io/restauranty-items
  tag: latest
  port: 3003
  replicas: 1

# ============================================================
# Frontend
# ============================================================
frontend:
  image: ireneandjoaoacr.azurecr.io/restauranty-client
  tag: latest
  port: 80
  replicas: 1
  serverUrl: 'http://localhost:80' #We have to change this when we have an ingress value

# ============================================================
# Prometheus
# ============================================================
prometheus:
  server:
    persistentVolume:
      enabled: true
      size: 8Gi
      storageClass: 'default'
    serverFiles:
      prometheus.yml:
        global:
          scrape_interval: 15s
        scrape_configs:
          - job_name: 'restauranty-auth'
            static_configs:
              - targets: ['auth:3001']
          - job_name: 'restauranty-discounts'
            static_configs:
              - targets: ['discounts:3002']
          - job_name: 'restauranty-items'
            static_configs:
              - targets: ['items:3003']
          - job_name: 'restauranty-frontend'
            static_configs:
              - targets: ['frontend:80']
