apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: {{ .Values.auth.port }}
      targetPort: {{ .Values.auth.port }}
  type: ClusterIP
