apiVersion: v1
kind: Service
metadata:
  name: discounts
spec:
  selector:
    app: discounts
  ports:
    - protocol: TCP
      port: { { .Values.discounts.port } }
      targetPort: { { .Values.discounts.port } }
  type: ClusterIP
