apiVersion: apps/v1
kind: Deployment
metadata:
  name: items
  labels:
    app: items
spec:
  replicas: {{ .Values.items.replicas }}
  selector:
    matchLabels:
      app: items
  template:
    metadata:
      labels:
        app: items
    spec:
      containers:
        - name: items
          image: "{{ .Values.items.image }}:{{ .Values.items.tag }}"
          ports:
            - containerPort: {{ .Values.items.port }}
          env:
            - name: PORT
              value: "{{ .Values.items.port }}"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: restauranty-secrets
                  key: MONGODB_URI
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: restauranty-secrets
                  key: SECRET
            - name: CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: restauranty-secrets
                  key: CLOUD_NAME
            - name: CLOUD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: restauranty-secrets
                  key: CLOUD_API_KEY
            - name: CLOUD_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: restauranty-secrets
                  key: CLOUD_API_SECRET