apiVersion: v1
kind: Secret
metadata:
  name: restauranty-secrets
type: Opaque
stringData:
  SECRET: "ireneandjoao_secret_key"
  MONGODB_URI: "mongodb://localhost:27017/restauranty"
  CLOUD_NAME: "dy3unbhws"
  CLOUD_API_KEY: "798263246623974"
  CLOUD_API_SECRET: "yENpqc2EJWL0_I7vipbTVbKaSG0"