apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube-db
  template:
    metadata:
      labels:
        app: sonarqube-db
    spec:
      containers:
        - name: postgresql
          image: postgres:15-alpine
          env:
            - name: POSTGRES_USER
              value: sonarqube
            - name: POSTGRES_PASSWORD
              value: sonarqube
            - name: POSTGRES_DB
              value: sonarqube
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube-db
spec:
  selector:
    app: sonarqube-db
  ports:
    - port: 5432
      targetPort: 5432